# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op1Numbers', models.IntegerField()),
                ('op2Numbers', models.IntegerField()),
                ('op3Numbers', models.IntegerField()),
                ('op4Numbers', models.IntegerField()),
            ],
        ),
    ]
