# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_responces'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgNumber', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
