# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='numCorrect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='numIncorrect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
