# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160517_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='form',
            field=models.IntegerField(default=0),
        ),
    ]
