# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_person_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='isMale',
            field=models.IntegerField(default=1),
        ),
    ]
