# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-30 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_person_lastfirstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lastFirstName',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
    ]
