# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20160530_1327'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responces',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='form',
            new_name='Form',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='imgNumber',
            new_name='ImgNumber',
        ),
        migrations.RemoveField(
            model_name='person',
            name='isMale',
        ),
        migrations.RemoveField(
            model_name='person',
            name='name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='numCorrect',
        ),
        migrations.RemoveField(
            model_name='person',
            name='numIncorrect',
        ),
        migrations.AddField(
            model_name='person',
            name='FirstName',
            field=models.CharField(default='FIRST NAME MISSING', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='Gender',
            field=models.CharField(default='NO_GENDER', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='LastName',
            field=models.CharField(default='LAST NAME MISSING', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='NickName',
            field=models.CharField(default='NICK NAME MISSING', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='NumCorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='NumIncorrect',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='UnformattedName',
            field=models.CharField(default='UNFORMATTED NAME MISSING', max_length=200),
        ),
    ]
