# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20160924_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='NumShown',
            field=models.IntegerField(default=0),
        ),
    ]
