# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-24 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_person_numshown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(default='USERNAME MISSING', max_length=200)),
                ('QuestionsAnswered', models.IntegerField(default=0)),
                ('AnswersCorrect', models.IntegerField(default=0)),
                ('AnswersIncorrect', models.IntegerField(default=0)),
                ('ImgNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
