# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='CorrectPercentage',
            field=models.FloatField(default=0.0),
        ),
    ]
